/**
 * Exercise Bank — каталог упражнений (v2)
 *
 * Поля:
 *   id              — стабильный slug
 *   name            — отображаемое имя (RU)
 *   muscles         — основные группы мышц
 *   equipment       — barbell|dumbbell|machine|cable|bodyweight|band
 *   type            — weighted_reps|bodyweight_reps|weighted_time|time_only|distance_time
 *   shoulderFriendly— безопасно для плеча (выключает фильтр shoulder_pain)
 *   loadsAnteriorDelt — low|med|high (нагрузка на переднюю дельту)
 *   alts            — id альтернативных упражнений (для замены)
 *   stepKg          — шаг прогрессии веса
 *   stepReps        — шаг прогрессии повторений
 *   stepTimeSec     — шаг прогрессии секунд (для time-based)
 *   defaultRest     — стандартный отдых между подходами, сек
 *   level           — beginner|intermediate|advanced
 *   prehab          — упражнение из разминки/префаба
 *   videoUrl        — пользовательская ссылка (можно вставить вручную)
 *   videoSearchQuery— готовый поисковый запрос YouTube
 *   tags            — compound|isolation|core|prehab|cardio
 */

const EXERCISE_BANK = [
  // ============ CHEST ============
  {
    id: 'dumbbell-press-neutral',
    name: 'Жим гантелей нейтральным хватом лёжа',
    muscles: ['chest', 'triceps', 'front_delt'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'low',
    alts: ['floor-press-dumbbell', 'machine-chest-press', 'dumbbell-incline-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'neutral grip dumbbell bench press tutorial',
  },
  {
    id: 'barbell-bench-press',
    name: 'Жим штанги лёжа',
    muscles: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-press-neutral', 'machine-chest-press', 'floor-press-dumbbell'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'barbell bench press proper form tutorial',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Жим гантелей лёжа',
    muscles: ['chest', 'triceps', 'front_delt'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-press-neutral', 'machine-chest-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell bench press tutorial',
  },
  {
    id: 'barbell-incline-press-low',
    name: 'Жим штанги на наклонной 15°',
    muscles: ['chest', 'front_delt', 'triceps'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-incline-press', 'machine-chest-press'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'low incline barbell bench press 15 degrees tutorial',
  },
  {
    id: 'dumbbell-incline-press',
    name: 'Жим гантелей на наклонной скамье',
    muscles: ['chest', 'front_delt', 'triceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-press-neutral', 'machine-chest-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'incline dumbbell bench press tutorial',
  },
  {
    id: 'floor-press-dumbbell',
    name: 'Floor press с гантелями',
    muscles: ['chest', 'triceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'low',
    alts: ['dumbbell-press-neutral', 'machine-chest-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell floor press tutorial',
  },
  {
    id: 'landmine-press',
    name: 'Landmine press одной рукой',
    unilateral: 'arm',
    muscles: ['chest', 'front_delt', 'triceps'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'med',
    alts: ['dumbbell-press-neutral', 'machine-chest-press'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'one arm landmine press tutorial',
  },
  {
    id: 'machine-chest-press',
    name: 'Жим в тренажёре',
    muscles: ['chest', 'triceps', 'front_delt'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'med',
    alts: ['dumbbell-press-neutral', 'pec-deck'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'machine chest press tutorial',
  },
  {
    id: 'pec-deck',
    name: 'Бабочка (pec deck)',
    muscles: ['chest'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'low',
    alts: ['dumbbell-fly', 'cable-crossover-high'],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'pec deck fly machine tutorial',
  },
  {
    id: 'dumbbell-fly',
    name: 'Разведение гантелей лёжа',
    muscles: ['chest'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'low',
    alts: ['pec-deck', 'cable-crossover-high'],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'flat dumbbell fly chest tutorial',
  },
  {
    id: 'cable-crossover-high',
    name: 'Кроссовер сверху вниз',
    muscles: ['chest'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'low',
    alts: ['dumbbell-fly', 'pec-deck'],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'high to low cable crossover tutorial',
  },
  {
    id: 'cable-crossover-low',
    name: 'Кроссовер снизу вверх',
    muscles: ['chest'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'med',
    alts: ['dumbbell-fly', 'pec-deck'],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'low to high cable crossover tutorial',
  },
  {
    id: 'pushup',
    name: 'Отжимания от пола',
    muscles: ['chest', 'triceps', 'front_delt', 'core'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'med',
    alts: ['machine-chest-press', 'dumbbell-press-neutral'],
    stepReps: 1,
    defaultRest: 60,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'proper push-up form tutorial',
  },
  {
    id: 'dip-chest',
    name: 'Отжимания на брусьях (грудь)',
    muscles: ['chest', 'triceps', 'front_delt'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-press-neutral', 'machine-chest-press'],
    stepReps: 1,
    defaultRest: 90,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'chest dips parallel bars tutorial',
  },

  // ============ BACK ============
  {
    id: 'pullup-pronated',
    name: 'Подтягивания прямым хватом',
    muscles: ['lats', 'biceps', 'rear_delt'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['lat-pulldown-wide', 'lat-pulldown-neutral'],
    stepReps: 1,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'pull up proper form pronated grip tutorial',
  },
  {
    id: 'pullup-supinated',
    name: 'Подтягивания обратным хватом',
    muscles: ['lats', 'biceps'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['lat-pulldown-neutral', 'pullup-pronated'],
    stepReps: 1,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'chin up supinated grip tutorial',
  },
  {
    id: 'lat-pulldown-wide',
    name: 'Тяга верхнего блока к груди',
    muscles: ['lats', 'biceps', 'rear_delt'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['lat-pulldown-neutral', 'pullup-pronated'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'wide grip lat pulldown tutorial',
  },
  {
    id: 'lat-pulldown-neutral',
    name: 'Тяга верхнего блока нейтральным хватом',
    muscles: ['lats', 'biceps'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['lat-pulldown-wide', 'seated-cable-row'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'neutral grip lat pulldown tutorial',
  },
  {
    id: 'seated-cable-row',
    name: 'Горизонтальная тяга в блоке',
    muscles: ['lats', 'biceps', 'rear_delt', 'mid_back'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['barbell-row', 'dumbbell-row'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'seated cable row tutorial',
  },
  {
    id: 'barbell-row',
    name: 'Тяга штанги в наклоне',
    muscles: ['lats', 'mid_back', 'biceps', 'rear_delt'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['dumbbell-row', 'seated-cable-row'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'barbell bent over row proper form tutorial',
  },
  {
    id: 'dumbbell-row',
    name: 'Тяга гантели одной рукой',
    unilateral: 'arm',
    muscles: ['lats', 'mid_back', 'biceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['barbell-row', 'seated-cable-row'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'one arm dumbbell row tutorial',
  },
  {
    id: 't-bar-row',
    name: 'Тяга Т-грифа',
    muscles: ['lats', 'mid_back', 'biceps', 'rear_delt'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['barbell-row', 'seated-cable-row'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'T-bar row proper form tutorial',
  },
  {
    id: 'dumbbell-shrug',
    name: 'Шраги с гантелями',
    muscles: ['traps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell shrugs traps tutorial',
  },
  {
    id: 'hyperextension',
    name: 'Гиперэкстензия',
    muscles: ['lower_back', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: [],
    stepReps: 1,
    defaultRest: 60,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'back extension hyperextension tutorial',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Pullover с гантелью',
    muscles: ['lats', 'chest'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'med',
    alts: [],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'intermediate',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell pullover tutorial',
  },

  // ============ LEGS ============
  {
    id: 'back-squat',
    name: 'Приседания со штангой',
    muscles: ['quads', 'glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['goblet-squat', 'leg-press'],
    stepKg: 2.5,
    defaultRest: 150,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'barbell back squat proper form tutorial',
  },
  {
    id: 'goblet-squat',
    name: 'Гоблет-приседания',
    muscles: ['quads', 'glutes', 'core'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['back-squat', 'leg-press'],
    stepKg: 2.5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'goblet squat tutorial',
  },
  {
    id: 'leg-press',
    name: 'Жим ногами в тренажёре',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['back-squat', 'goblet-squat'],
    stepKg: 5,
    defaultRest: 120,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'leg press machine tutorial',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Болгарские сплит-приседания',
    unilateral: 'leg',
    muscles: ['quads', 'glutes'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['dumbbell-lunge', 'goblet-squat'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'bulgarian split squat tutorial',
  },
  {
    id: 'dumbbell-lunge',
    name: 'Выпады с гантелями',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['bulgarian-split-squat', 'leg-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell walking lunges tutorial',
  },
  {
    id: 'rdl-barbell',
    name: 'Румынская тяга со штангой',
    muscles: ['hamstrings', 'glutes', 'lower_back'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['rdl-dumbbell', 'hyperextension'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'romanian deadlift barbell proper form tutorial',
  },
  {
    id: 'rdl-dumbbell',
    name: 'Румынская тяга с гантелями',
    muscles: ['hamstrings', 'glutes', 'lower_back'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['rdl-barbell', 'hyperextension'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'romanian deadlift dumbbell tutorial',
  },
  {
    id: 'deadlift-conventional',
    name: 'Становая тяга классическая',
    muscles: ['hamstrings', 'glutes', 'lower_back', 'lats', 'traps'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['deadlift-sumo', 'rdl-barbell'],
    stepKg: 5,
    defaultRest: 180,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'conventional deadlift proper form tutorial',
  },
  {
    id: 'deadlift-sumo',
    name: 'Становая тяга сумо',
    muscles: ['quads', 'glutes', 'hamstrings', 'lower_back'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['deadlift-conventional', 'rdl-barbell'],
    stepKg: 5,
    defaultRest: 180,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'sumo deadlift proper form tutorial',
  },
  {
    id: 'leg-curl',
    name: 'Сгибание ног в тренажёре',
    muscles: ['hamstrings'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'lying leg curl machine tutorial',
  },
  {
    id: 'leg-extension',
    name: 'Разгибание ног в тренажёре',
    muscles: ['quads'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'leg extension machine tutorial',
  },
  {
    id: 'calf-raise-standing',
    name: 'Подъём на носки стоя',
    muscles: ['calves'],
    equipment: 'machine',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 2.5,
    defaultRest: 45,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'standing calf raise tutorial',
  },
  {
    id: 'hip-thrust',
    name: 'Hip thrust со штангой',
    muscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['rdl-barbell'],
    stepKg: 5,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'barbell hip thrust tutorial',
  },

  // ============ SHOULDERS ============
  {
    id: 'dumbbell-shoulder-press-neutral',
    name: 'Жим гантелей сидя нейтральным хватом',
    muscles: ['front_delt', 'side_delt', 'triceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    loadsAnteriorDelt: 'med',
    alts: ['arnold-press', 'machine-chest-press'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'beginner',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'neutral grip seated dumbbell shoulder press tutorial',
  },
  {
    id: 'ohp-barbell',
    name: 'Жим штанги стоя (OHP)',
    muscles: ['front_delt', 'side_delt', 'triceps', 'core'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-shoulder-press-neutral', 'arnold-press'],
    stepKg: 2.5,
    defaultRest: 120,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'standing overhead press barbell tutorial',
  },
  {
    id: 'arnold-press',
    name: 'Жим Арнольда',
    muscles: ['front_delt', 'side_delt', 'triceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['dumbbell-shoulder-press-neutral'],
    stepKg: 1.25,
    defaultRest: 90,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'arnold press tutorial',
  },
  {
    id: 'lateral-raise',
    name: 'Махи гантелями в стороны',
    muscles: ['side_delt'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 1.25,
    defaultRest: 45,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell lateral raise tutorial',
  },
  {
    id: 'rear-delt-fly',
    name: 'Махи в наклоне (задняя дельта)',
    muscles: ['rear_delt'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['face-pull'],
    stepKg: 1.25,
    defaultRest: 45,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'bent over rear delt fly tutorial',
  },
  {
    id: 'face-pull',
    name: 'Face pulls',
    muscles: ['rear_delt', 'rotator_cuff', 'rhomboids'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    prehab: true,
    alts: ['rear-delt-fly', 'band-pull-apart'],
    stepKg: 1.25,
    defaultRest: 45,
    level: 'beginner',
    tags: ['isolation', 'prehab'],
    videoUrl: '',
    videoSearchQuery: 'face pull cable proper form tutorial',
  },
  {
    id: 'band-pull-apart',
    name: 'Band pull-aparts',
    muscles: ['rear_delt', 'rhomboids'],
    equipment: 'band',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    prehab: true,
    alts: ['face-pull'],
    stepReps: 1,
    defaultRest: 30,
    level: 'beginner',
    tags: ['isolation', 'prehab'],
    videoUrl: '',
    videoSearchQuery: 'band pull apart shoulder warmup tutorial',
  },
  {
    id: 'external-rotation-band',
    name: 'External rotation с резинкой',
    muscles: ['rotator_cuff'],
    equipment: 'band',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    prehab: true,
    alts: [],
    stepReps: 1,
    defaultRest: 30,
    level: 'beginner',
    tags: ['isolation', 'prehab'],
    videoUrl: '',
    videoSearchQuery: 'band external rotation shoulder rotator cuff tutorial',
  },

  // ============ ARMS ============
  {
    id: 'dumbbell-curl',
    name: 'Сгибание гантелей на бицепс',
    muscles: ['biceps'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['barbell-curl', 'hammer-curl'],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'dumbbell bicep curl proper form tutorial',
  },
  {
    id: 'barbell-curl',
    name: 'Сгибание со штангой',
    muscles: ['biceps'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['dumbbell-curl', 'hammer-curl'],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'barbell bicep curl tutorial',
  },
  {
    id: 'hammer-curl',
    name: 'Молотки (hammer curl)',
    muscles: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['dumbbell-curl'],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'hammer curl tutorial',
  },
  {
    id: 'skullcrusher',
    name: 'Французский жим лёжа',
    muscles: ['triceps'],
    equipment: 'barbell',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['cable-triceps-pushdown'],
    stepKg: 1.25,
    defaultRest: 60,
    level: 'intermediate',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'skullcrusher lying triceps extension tutorial',
  },
  {
    id: 'cable-triceps-pushdown',
    name: 'Разгибание на трицепс в блоке',
    muscles: ['triceps'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: ['skullcrusher'],
    stepKg: 2.5,
    defaultRest: 60,
    level: 'beginner',
    tags: ['isolation'],
    videoUrl: '',
    videoSearchQuery: 'triceps pushdown cable tutorial',
  },
  {
    id: 'dip-triceps',
    name: 'Отжимания на брусьях (трицепс)',
    muscles: ['triceps', 'chest', 'front_delt'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: false,
    loadsAnteriorDelt: 'high',
    alts: ['cable-triceps-pushdown', 'skullcrusher'],
    stepReps: 1,
    defaultRest: 90,
    level: 'intermediate',
    tags: ['compound'],
    videoUrl: '',
    videoSearchQuery: 'triceps dip parallel bars tutorial',
  },

  // ============ CORE ============
  {
    id: 'plank',
    name: 'Планка',
    muscles: ['core'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: ['side-plank'],
    stepTimeSec: 5,
    defaultRest: 45,
    level: 'beginner',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'front plank proper form tutorial',
  },
  {
    id: 'side-plank',
    name: 'Планка боковая',
    unilateral: 'side',
    muscles: ['core', 'obliques'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: ['plank'],
    stepTimeSec: 5,
    defaultRest: 45,
    level: 'beginner',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'side plank proper form tutorial',
  },
  {
    id: 'crunch',
    name: 'Скручивания',
    muscles: ['core'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['bicycle-crunch'],
    stepReps: 2,
    defaultRest: 45,
    level: 'beginner',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'crunch abs proper form tutorial',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Подъём ног в висе',
    muscles: ['core', 'hip_flexors'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['crunch'],
    stepReps: 1,
    defaultRest: 60,
    level: 'intermediate',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'hanging leg raise tutorial',
  },
  {
    id: 'pallof-press',
    name: 'Pallof press',
    muscles: ['core', 'obliques'],
    equipment: 'cable',
    type: 'weighted_reps',
    shoulderFriendly: true,
    alts: [],
    stepKg: 2.5,
    defaultRest: 45,
    level: 'beginner',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'pallof press anti rotation tutorial',
  },
  {
    id: 'bicycle-crunch',
    name: 'Велосипед',
    muscles: ['core', 'obliques'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['crunch'],
    stepReps: 2,
    defaultRest: 45,
    level: 'beginner',
    tags: ['core'],
    videoUrl: '',
    videoSearchQuery: 'bicycle crunch abs tutorial',
  },

  // ============ OUTDOOR / MORNING ROUTINE ============
  {
    id: 'jumping-jack',
    name: 'Прыжки «звёздочка» (jumping jacks)',
    muscles: ['cardio', 'calves', 'side_delt'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 10,
    defaultRest: 15,
    level: 'beginner',
    tags: ['cardio', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'jumping jacks tutorial proper form',
  },
  {
    id: 'neck-shoulder-rolls',
    name: 'Разминка шеи и плеч',
    muscles: ['traps', 'rear_delt'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 10,
    level: 'beginner',
    tags: ['mobility', 'morning', 'prehab'],
    videoUrl: '',
    videoSearchQuery: 'neck and shoulder rolls warm up tutorial',
  },
  {
    id: 'hip-circles',
    name: 'Круговые движения тазом',
    muscles: ['hip_flexors', 'core'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 10,
    level: 'beginner',
    tags: ['mobility', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'hip circles warm up tutorial',
  },
  {
    id: 'leg-swings',
    name: 'Махи ногой вперёд-назад',
    unilateral: 'leg',
    muscles: ['hip_flexors', 'hamstrings', 'glutes'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 10,
    level: 'beginner',
    tags: ['mobility', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'leg swings dynamic warm up tutorial',
  },
  {
    id: 'worlds-greatest-stretch',
    name: 'Самая большая растяжка (World\'s Greatest Stretch)',
    unilateral: 'leg',
    muscles: ['hip_flexors', 'hamstrings', 'core', 'rear_delt'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 10,
    defaultRest: 10,
    level: 'beginner',
    tags: ['mobility', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'worlds greatest stretch tutorial',
  },
  {
    id: 'cat-cow',
    name: 'Кошка-корова (cat-cow)',
    muscles: ['lower_back', 'core'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 10,
    defaultRest: 10,
    level: 'beginner',
    tags: ['mobility', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'cat cow stretch tutorial',
  },
  {
    id: 'cobra-stretch',
    name: 'Поза кобры',
    muscles: ['lower_back', 'core'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 10,
    defaultRest: 10,
    level: 'beginner',
    tags: ['stretching', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'cobra stretch yoga tutorial',
  },
  {
    id: 'squat-bodyweight',
    name: 'Приседания без веса',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['goblet-squat'],
    stepReps: 2,
    defaultRest: 30,
    level: 'beginner',
    tags: ['compound', 'morning', 'outdoor'],
    videoUrl: '',
    videoSearchQuery: 'bodyweight squat proper form tutorial',
  },
  {
    id: 'bar-hang',
    name: 'Вис на турнике (декомпрессия)',
    muscles: ['lats', 'forearms', 'core'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 30,
    level: 'beginner',
    tags: ['mobility', 'outdoor', 'morning', 'prehab'],
    videoUrl: '',
    videoSearchQuery: 'dead hang bar tutorial benefits',
  },
  {
    id: 'inverted-row',
    name: 'Австралийские подтягивания (inverted row)',
    muscles: ['lats', 'mid_back', 'biceps', 'rear_delt'],
    equipment: 'bodyweight',
    type: 'bodyweight_reps',
    shoulderFriendly: true,
    alts: ['pullup-pronated', 'lat-pulldown-neutral'],
    stepReps: 1,
    defaultRest: 60,
    level: 'beginner',
    tags: ['compound', 'outdoor'],
    videoUrl: '',
    videoSearchQuery: 'inverted row australian pull up tutorial',
  },
  {
    id: 'hamstring-stretch',
    name: 'Растяжка задней поверхности бедра',
    unilateral: 'leg',
    muscles: ['hamstrings'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 5,
    level: 'beginner',
    tags: ['stretching', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'hamstring stretch standing tutorial',
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Растяжка сгибателей бедра (выпад)',
    unilateral: 'leg',
    muscles: ['hip_flexors', 'quads'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 5,
    level: 'beginner',
    tags: ['stretching', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'hip flexor stretch lunge tutorial',
  },
  {
    id: 'shoulder-pec-stretch',
    name: 'Растяжка груди и плеча на турнике',
    unilateral: 'arm',
    muscles: ['chest', 'front_delt'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 5,
    level: 'beginner',
    tags: ['stretching', 'morning', 'outdoor'],
    videoUrl: '',
    videoSearchQuery: 'doorway pec stretch tutorial',
  },
  {
    id: 'calf-stretch',
    name: 'Растяжка икр',
    unilateral: 'leg',
    muscles: ['calves'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 5,
    defaultRest: 5,
    level: 'beginner',
    tags: ['stretching', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'standing calf stretch tutorial',
  },
  {
    id: 'child-pose',
    name: 'Поза ребёнка (child\'s pose)',
    muscles: ['lower_back', 'lats'],
    equipment: 'bodyweight',
    type: 'time_only',
    shoulderFriendly: true,
    alts: [],
    stepTimeSec: 10,
    defaultRest: 5,
    level: 'beginner',
    tags: ['stretching', 'morning'],
    videoUrl: '',
    videoSearchQuery: 'childs pose yoga tutorial',
  },
];

// Индекс по id для O(1) lookup
const EXERCISE_BY_ID = Object.fromEntries(EXERCISE_BANK.map(e => [e.id, e]));

// Хелперы
function getExerciseById(id) {
  return EXERCISE_BY_ID[id] || null;
}

function searchExercises({ query = '', muscle = null, equipment = null, shoulderFriendlyOnly = false, level = null } = {}) {
  const q = (query || '').toLowerCase().trim();
  return EXERCISE_BANK.filter(e => {
    if (q && !e.name.toLowerCase().includes(q) && !e.id.includes(q)) return false;
    if (muscle && !e.muscles.includes(muscle)) return false;
    if (equipment && e.equipment !== equipment) return false;
    if (shoulderFriendlyOnly && !e.shoulderFriendly) return false;
    if (level && e.level !== level) return false;
    return true;
  });
}

function getMuscleGroups() {
  const set = new Set();
  EXERCISE_BANK.forEach(e => e.muscles.forEach(m => set.add(m)));
  return Array.from(set).sort();
}

function getEquipmentTypes() {
  return ['barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'band'];
}

// Видео: либо пользовательский URL, либо поисковый URL YouTube
function getExerciseVideoUrl(exercise) {
  if (!exercise) return '';
  if (exercise.videoUrl) return exercise.videoUrl;
  if (exercise.videoSearchQuery) {
    return 'https://www.youtube.com/results?search_query=' + encodeURIComponent(exercise.videoSearchQuery);
  }
  return '';
}

window.EXERCISE_BANK = EXERCISE_BANK;
window.EXERCISE_BY_ID = EXERCISE_BY_ID;
window.getExerciseById = getExerciseById;
window.searchExercises = searchExercises;
window.getMuscleGroups = getMuscleGroups;
window.getEquipmentTypes = getEquipmentTypes;
window.getExerciseVideoUrl = getExerciseVideoUrl;

console.log('📦 exercise-bank.js loaded:', EXERCISE_BANK.length, 'exercises');
